modLoader="lowcodefml"
loaderVersion="[47,)"
license="CC BY-NC-SA"
issueTrackerURL="https://github.com/RickieGamer/Quark_Engineering/issues"

[[mods]]
modId="quarkengineering"
version="1.1"
displayName="Quark Engineering"
description="Immersive Engineering and Quark recipe compat "
authors="RickieGamer"


[[dependencies.quarkengineering]]
    modId="immersiveengineering"
    versionRange="[1.20.1-10.0.0-169,)"
    mandatory=true
    ordering="AFTER"

[[dependencies.quarkengineering]]
    modId="quark"
    versionRange="[0,)"
    mandatory=true
    ordering="AFTER"